name: telex
version: 0.1.8+9
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.4
  package_info: ^2.0.2
  feather_icons_flutter: ^4.7.4
  url_launcher: ^6.0.12
  flutter_html: ^2.1.5
  share: ^2.0.4
  timeago: ^3.1.0
  dynamic_theme:
    git: "https://github.com/Norbert515/dynamic_theme.git"
  photo_view: ^0.13.0
  path: ^1.7.0
  toast: ^0.1.5
  permission_handler: ^8.2.2
  shared_preferences: ^2.0.5
  flutter_spinkit: ^5.1.0
  flutter_custom_tabs: ^1.0.3 
  intl: 0.17.0
  # flutter_local_notifications: ^2.0.0
  # workmanager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/profile.png

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700