name: telex

version: 0.1.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  package_info: ^0.4.3
  feather_icons_flutter: ^4.7.4
  url_launcher: ^5.7.2
  flutter_html: ^1.0.0
  share: ">=0.6.4 <2.0.0"
  google_fonts: ^1.0.0
  timeago: ^2.0.26
  flutter_linkify: ^3.1.3
  dynamic_theme:
    git: "https://github.com/Norbert515/dynamic_theme.git"
  photo_view: ^0.10.2
  path: ^1.7.0
  crypto: ^2.1.5
  toast: ^0.1.5
  permission_handler: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
